
<div class="container-fluid h-100 ml-2">
    <div class="row h-100">
    <div class="row justify-content-center w-100">
        <div class="box col-11 col-md-6 col-lg-4">
            <h6 class="text-center">Faça login para ter acesso à carteirinha de associado:</h6>
            <form method="post" action="/autenticar">
                <div class="form-group">
                    <input type="email" name="email" class="form-control" placeholder="E-mail" required>
                </div>
                <div class="form-group">
                    <input type="password" name="senha" class="form-control" placeholder="Senha" required>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Entrar</button>

                <?php if($this->view->login == 'erro'){ ?>
                <div class="mt-3 text-danger text-center">*E-mail e/ou senha inválido(s)</div>
                <?php } ?>
            </form>

            <div class="text-center mt-4">
                <img class="imagempng" src="/img/logobranca.jpg" alt="Logo">
                <h1 class="mt-3">Atlética Fisioterapia</h1>
                <h2 class="mt-3">Seja um associado da nossa atlética!</h2>
                <a href="/inscreverse" class="btn btn-primary btn-block mt-3">Inscrever-se</a>
            </div>
        </div>
    </div>
</div>
