<div class="container">

    <div class="d-flex justify-content-center">
		<img class="align-items-center imagempng" src="/img/logo.jpg" />
	</div>

    <div class="d-row justify-content-center">
    
        <h1 class="align-items-center title">Bem-vindo à nossa atlética !!!</h1>

        <h6 class="align-items-center">
            Efetue o pagameto do valor semestral para obter o ascesso a sua carteira de associado da atletica.
            <br>
            <br>
            O pagamento pode ser feito pelo pix:
            <br>
            marianaassato67@gmail.com
            <br>
            <small>Mandar comprovante no whatsapp</small>
            <br>
            <br>
            Ou pelos cartões de créditou ou debito:
            <br>
            <small>
                Caso o pagamento quiser ser feito por cartao de credito ou debito, o o pagemento devera ser efetuado presencialmente. 
                <br>
                consultar as taxas de juros e parcelamento com os administradores da atletica.
            </small>
            <br>
            <br>
            Após o pagamentos sua carterinha estara disponivem em ate 48h, ou podera pedir a confirmação do pagamento direto com os administradores da atletica.
            <br>
            <br>
            Caso precise de ajuda, entre em contato com um de nossos administradores:
            <br>
            <br>
            <div class="contatocentro">
                Mariana Assato
                <br>
                <a class="link" href="https://w.app/rs0pz1">
                    <i class="fab fa-whatsapp wpp" style="color: #63E6BE;"></i>        
                    67 9 9306-8172
                </a>
                <br>
                <img class="qrwpp" src="/img/qrwppmariana.png" >
                </div>
        </h6>
    </div>

</div>